name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */6 * * *"   # cada 6 horas
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update GitHub activity section
        uses: Readme‑Workflows/recent‑activity@v1.0.0
        with:
          github_token: ${{ secrets.TOKEN }}
          username: Danieloneone
          output_file: README.md
          max_records: 10
          include_private: false

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "⚡ Update GitHub activity" && git push

