name: Update GitHub Activity in index.md

on:
  schedule:
    - cron: "0 * * * *" # cada hora
  workflow_dispatch:     # permite ejecutarlo manualmente
  push:                  # tambiÃ©n se ejecuta si haces un commit
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update GitHub activity
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        with:
          GH_USERNAME: Danieloneone
          COMMIT_MSG: "âš¡ Actualizar actividad de GitHub"
          MAX_LINES: 10
          README_FILE: "index.md"  # ðŸ‘ˆ importante: tu archivo .md

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

