name: Update activity log

on:
  schedule:
    - cron: '0 */6 * * *'   # cada 6 horas
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update activity
        uses: Readme-Workflows/recent-activity@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
