name: Update Activity Log

on:
  schedule:
    - cron: "0 */6 * * *"  # ejecuta cada 6 horas
  workflow_dispatch:        # permite ejecuci√≥n manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
